# Generated by Django 5.0 on 2024-01-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name': 'College'},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
