# Generated by Django 5.0 on 2024-01-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_student_id'),
        ('home', '0010_alter_college_options_alter_product_slug'),
    ]

    operations = [
    ]
