# Generated by Django 5.0 on 2024-01-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_abc_created_at_abc_this_field_is_from_basemodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
