# Generated by Django 5.0 on 2024-01-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_abc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_table',
        ),
    ]
