# Generated by Django 5.0 on 2024-01-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
    ]
