# Generated by Django 5.0 on 2024-01-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_product_description_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default=1, upload_to='product/files'),
            preserve_default=False,
        ),
    ]
