# Generated by Django 5.0.2 on 2024-02-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
